name: Rename Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  rename:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Rename PR Title
        uses: actions/github-script@v9
        with:
          script: |
            const title = context.payload.pull_request.title;
            if (title.startsWith("chore(deps):") || title.startsWith("chore(deps-dev):")) {
              const newTitle = title.replace(/^chore\(deps(?:-dev)?\):/, "chore:");
              console.log(`Renaming PR #${context.payload.pull_request.number} from "${title}" to "${newTitle}"`);
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                title: newTitle
              });
            } else {
              console.log("PR title does not match prefix target.");
            }